<footer class= "page-footer">
	<div class = "container">
		<div class = "row">
				<h4 class = "white-text">About us:</h4>
				<p class = "flow-text">Team 5, CSC174 Advance Front-End Web Development</p>
		</div>
	</div>
	<div class ="footer-copyright">
		<div class ="container">
			Content taken from:<a href="<?php echo $contentFrom ?>" class="waves-effect waves-light btn"><?php echo "$sportName" ?>Wikipedia</a>
		</div>
	</div>			
</footer>