
      <nav>
        <div class="nav-wrapper">
            <ul class="left hide-on-med-and-down">
                  <a href="index.php" class="brand-logo center">Sports</a>
          <li><a href="soccer.php">Soccer</a></li>
          <li><a href="frisbee.php">Frisbee</a></li>
          <li><a href="baseball.php">Baseball</a></li>
          <li><a href="colophon.php">Colophon</a></li>
        </ul>
            </div>
      </nav>
