<nav>
    <div class="nav-wrapper">
      <a href="index.php" class="brand-logo center">Home</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
         <li><a href="soccer.php">Soccer</a></li>
          <li><a href="frisbee.php">Frisbee</a></li>
          <li><a href="baseball.php">Baseball</a></li>
          <li><a href="colophon.php">Colophon</a></li>
      </ul>
    </div>
  </nav>
