<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title> CSC174 Project1 | <?php echo "$currentPage"; ?></title>
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="css/materialize.min.css">
		<link rel="stylesheet" href="css/styles.css">
	</head>
	<body>

	<!-- <div class="carousel carousel-slider">
	    <a class="carousel-item" href="#soccer.php"><img src="images/carousel/soccer.jpg" alt="soccer"></a>
	    <a class="carousel-item" href="#frisbee.php"><img src="images/carousel/frisbee.jpg" alt="frisbee"></a>
	    <a class="carousel-item" href="#baseball.php"><img src="images/carousel/baseball.jpg" alt="baseball"></a>
  	</div> -->

	<div class="container">
	<header>
		<h1>
			Sports!
		</h1>

	</header>

